# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-12 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20180412_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='ct',
            new_name='category',
        ),
    ]
