# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-12 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20180412_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('\u57f9\u8bad\u673a\u6784', 'pxjg'), ('\u9ad8\u6821', 'gx'), ('\u4e2a\u4eba', 'gr')], default='pxjg', max_length=20, verbose_name='\u673a\u6784\u7c7b\u522b'),
        ),
    ]
