# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-18 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(default='', max_length=50, verbose_name='\u8bbf\u95ee\u5730\u5740'),
        ),
    ]
